[package]
name = "address_comment_loader"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
encoding_rs = "0.8"
encoding_rs_io = "0.1"
log = "0.4"
flexi_logger = "0.27"
serde = { version = "1.0", features = ["derive"] }
config = "0.14"
